# Generated by Django 6.1 on 2026-08-19 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(default='UM-', max_length=20, unique=True, verbose_name='Staff ID')),
                ('ic_number', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='No. KP / IC Number')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Penuh / Full Name')),
                ('role', models.CharField(choices=[('SL', 'Ketua Syif / Shift Leader'), ('AL', 'Penolong Ketua / Assistant Leader'), ('OF', 'Anggota / Officer')], default='OF', max_length=2, verbose_name='Pangkat / Rank')),
                ('staff_group', models.CharField(max_length=50, verbose_name='Kumpulan / Squad Group')),
                ('placement', models.CharField(max_length=100, verbose_name='Penempatan / Duty Placement')),
                ('roster_type', models.CharField(choices=[('ROT', 'Standard Rotation (2A, 2M, 1Off, 1N, 1Off)'), ('MORN', 'Special Roster (Morning Only / Syif Pagi Sahaja)')], default='ROT', max_length=4, verbose_name='Profil Roster / Roster Profile')),
            ],
            options={
                'verbose_name': 'Senarai Anggota',
                'verbose_name_plural': '1. Senarai Anggota',
            },
        ),
        migrations.CreateModel(
            name='DailyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarikh / Date')),
                ('roster_type', models.CharField(choices=[('M', 'Morning / Pagi (07:00 - 16:00)'), ('A', 'Afternoon / Petang (15:00 - 24:00)'), ('N', 'Night / Malam (23:00 - 08:00)'), ('M_FRI', 'Morning / Pagi (07:30 - 16:00) [Jumaat Sahaja]'), ('A_FRI', 'Afternoon / Petang (15:30 - 24:00) [Jumaat Sahaja]'), ('OFF', 'Cuti Rehat / Day Off'), ('EL', 'Cuti Kecemasan / Emergency Leave')], max_length=5, verbose_name='Pergerakan Syif / Assigned Shift')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nota / Notes')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.officer', verbose_name='Anggota / Officer')),
            ],
            options={
                'verbose_name': 'Master Roster Harian',
                'verbose_name_plural': '2. Master Roster Harian',
                'unique_together': {('officer', 'date')},
            },
        ),
    ]
