# Generated by Django 6.1 on 2026-08-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='staff_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='No. Pekerja / Staff Number'),
        ),
    ]
