# Generated by Django 6.1 on 2026-08-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_officer_staff_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyroster',
            options={'verbose_name': 'Jadual Harian', 'verbose_name_plural': '2. Rekod Pergerakan Syif Bulanan'},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'verbose_name': 'Profil Anggota', 'verbose_name_plural': '1. Senarai Anggota'},
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='date',
            field=models.DateField(verbose_name='Tarikh Tugas'),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Penempatan / Tugas'),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='roster.officer', verbose_name='Anggota'),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='roster_type',
            field=models.CharField(default='OFF', max_length=20, verbose_name='Kod Syif'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='ic_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='No Kad Pengenalan'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Penuh'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='placement',
            field=models.CharField(default='Pintu Gerbang Utama', max_length=255, verbose_name='Penempatan Core Post'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='role',
            field=models.CharField(choices=[('SL', 'Ketua Syif / Shift Leader (SJN)'), ('AL', 'Penolong Ketua Syif / Assistant Leader (KPL)'), ('OF', 'Anggota / Constable (PB)')], default='OF', max_length=2, verbose_name='Pangkat'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='roster_type',
            field=models.CharField(default='ROT', max_length=10, verbose_name='Jenis Roster'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='staff_group',
            field=models.CharField(default='Kumpulan A', max_length=100, verbose_name='Kumpulan Skuad'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Staff ID (UM-XXXX)'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='staff_number',
            field=models.CharField(default='', max_length=50, verbose_name='No Staf'),
            preserve_default=False,
        ),
    ]
