# Generated by Django 6.1 on 2026-08-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_alter_dailyroster_options_alter_officer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='roster_type',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='staff_number',
        ),
        migrations.AlterField(
            model_name='officer',
            name='placement',
            field=models.CharField(choices=[('KETUA SYIF', 'KETUA SYIF'), ('PEMBANTU KETUA SYIF (PERONDA 1)', 'PEMBANTU KETUA SYIF (PERONDA 1)'), ('PEMBANTU KETUA SYIF (PERONDA 2)', 'PEMBANTU KETUA SYIF (PERONDA 2)'), ('KAWALAN(IPK)', 'KAWALAN(IPK)'), ('ZON A', 'ZON A'), ('ZON B', 'ZON B'), ('ZON C', 'ZON C'), ('ZON D', 'ZON D'), ('ZON E', 'ZON E'), ('ZON F', 'ZON F'), ('UNIT TRAFIK', 'UNIT TRAFIK'), ('GATE KUALA LUMPUR(GOLF1)', 'GATE KUALA LUMPUR(GOLF1)'), ('GATE PETALING JAYA(GOLF2)', 'GATE PETALING JAYA(GOLF2)'), ('GATE JALAN ILMU(GOLF3)', 'GATE JALAN ILMU(GOLF3)'), ('GATE FAKULTI BAHASA(GOLF4)', 'GATE FAKULTI BAHASA(GOLF4)'), ('GATE DAMANSARA(GOLF5)', 'GATE DAMANSARA(GOLF5)'), ('CANSELERI', 'CANSELERI'), ('GALERI', 'GALERI'), ('DEWAN TUNKU CANSELOR(DTC)', 'DEWAN TUNKU CANSELOR(DTC)'), ('RUMAH ANTARABANGSA(RAB)', 'RUMAH ANTARABANGSA(RAB)'), ('FAKULTI PERGIGIAN', 'FAKULTI PERGIGIAN'), ('UNIT SIASATAN/DETEKTIF', 'UNIT SIASATAN/DETEKTIF'), ('LAKIM/KK13', 'LAKIM/KK13'), ('WISMA R&D', 'WISMA R&D'), ('SEKSYEN LATIHAN & DISIPLIN', 'SEKSYEN LATIHAN & DISIPLIN'), ('UNIT PELEKAT', 'UNIT PELEKAT'), ('ROSTER/JADUAL TUGAS', 'ROSTER/JADUAL TUGAS')], default='GATE KUALA LUMPUR(GOLF1)', max_length=255, verbose_name='Penempatan Core Post'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='staff_group',
            field=models.CharField(default='Static (Morning Only)', max_length=100, verbose_name='Kumpulan Skuad'),
        ),
    ]
