# Generated by Django 6.1 on 2026-09-02 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_remove_officer_roster_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyroster',
            name='override_placement',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Penempatan Manual'),
        ),
        migrations.AddField(
            model_name='officer',
            name='shift_type',
            field=models.CharField(choices=[('ROT', 'Syif Berpusingan / Shift Rotation'), ('MORNING', 'Syif Statik Pagi Sahaja / Static Morning Only'), ('AFTERNOON', 'Syif Statik Petang Sahaja / Static Afternoon Only')], default='ROT', max_length=10, verbose_name='Jenis Syif'),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='roster.officer'),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='roster_type',
            field=models.CharField(default='X', max_length=20),
        ),
        migrations.AlterField(
            model_name='officer',
            name='ic_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IC Number / No Kad Pengenalan'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name / Nama Penuh'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='placement',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Place / Tempat'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role / Jawatan'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='staff_group',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Group / Kumpulan'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Staff ID / No Staf'),
        ),
    ]
