# Generated by Django 6.1 on 2026-09-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_dailyroster_override_placement_officer_shift_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyroster',
            options={'verbose_name': 'Jadual Harian', 'verbose_name_plural': 'Rekod Pergerakan Syif Bulanan'},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'verbose_name': 'Profil Anggota', 'verbose_name_plural': 'Senarai Anggota'},
        ),
        migrations.AlterField(
            model_name='officer',
            name='shift_type',
            field=models.CharField(choices=[('ROT', 'Syif Berpusingan / Shift Rotation'), ('MORNING', 'Syif Pagi Sahaja / Morning Shift Only'), ('AFTERNOON', 'Syif Petang Sahaja / Afternoon Shift Only')], default='ROT', max_length=10, verbose_name='Jenis Syif'),
        ),
    ]
