# Generated by Django 6.1 on 2026-09-10 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_alter_dailyroster_options_alter_officer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyroster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dailyroster',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.officer'),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='override_placement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyroster',
            name='roster_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='officer',
            name='ic_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='officer',
            name='placement',
            field=models.CharField(default='BELUM DITETAPKAN', max_length=255),
        ),
        migrations.AlterField(
            model_name='officer',
            name='role',
            field=models.CharField(default='KONST/PB', max_length=100),
        ),
        migrations.AlterField(
            model_name='officer',
            name='shift_type',
            field=models.CharField(default='ROT', max_length=20),
        ),
        migrations.AlterField(
            model_name='officer',
            name='staff_group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='officer',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='RosterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField()),
                ('shift_code', models.CharField(max_length=10)),
                ('placement_assigned', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by_excel', models.BooleanField(default=False)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.officer')),
            ],
        ),
    ]
