# Generated by Django 6.1 on 2026-09-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_alter_dailyroster_options_alter_officer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyroster',
            options={'verbose_name': 'Jadual Harian / Daily Roster', 'verbose_name_plural': '🗓️ 2. Jadual Tugas Harian / Daily Rosters'},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'verbose_name': 'Profil Anggota / Officer Profile', 'verbose_name_plural': '📂 1. Direktori Profil Anggota / Officers Directory'},
        ),
        migrations.AlterModelOptions(
            name='rosterhistory',
            options={'verbose_name': 'Log Sejarah / Roster History', 'verbose_name_plural': '📜 3. Log Audit Pertukaran / Roster Histories'},
        ),
    ]
