# Generated by Django 6.1 on 2026-09-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_alter_dailyroster_options_alter_officer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyroster',
            options={'verbose_name': 'Jadual Harian / Daily Roster', 'verbose_name_plural': '🗓️ 3. Jadual Tugas Harian / Daily Rosters'},
        ),
        migrations.AlterModelOptions(
            name='rosterhistory',
            options={'verbose_name': 'Log Sejarah / Roster History', 'verbose_name_plural': '📜 2. Log Audit Pertukaran / Roster Histories'},
        ),
    ]
