# Generated by Django 6.1 on 2026-09-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_alter_dailyroster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterhistory',
            name='source',
            field=models.CharField(blank=True, default='manual', max_length=50),
        ),
    ]
